server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:NexOS_Enterprise;DB_CLOSE_DELAY=-1;MODE=MSSQLServer
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

erp:
  security:
    rate-limit:
      auth-limit: 5
      api-limit: 100
    brute-force:
      max-attempts: 5
      lockout-minutes: 15
    firewall:
      whitelist-ips: 127.0.0.1,::1,0:0:0:0:0:0:0:1

juniper:
  cloud:
    enabled: true
    gateway-host: "juniper-srx.cloud.nexos.internal"
    port: 8443
    cluster-id: "JUNIPER-SRX-NEXOS-CLOUD-01"
    secintel-feed: "NexOS-ERP-Threats"
    sync-interval-seconds: 30

---
spring:
  config:
    activate:
      on-profile: sqlserver
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=NexOS_Enterprise;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Password@123
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2016Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

